name: Primeiro Workflow

on:
    push:
        branches: [ main ]

jobs:
    test_job:
        name: Executando o job de teste
        runs-on: ubuntu-latest
        steps:
            -name: Checkout code
             uses: actions/checkout@v2
             
             -name: Executando um comando simples
              run: echo "Primeiro Action feito no Github"